<?php

/**
 * Group
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Group extends BaseGroup
{
	public static function findAllAsChoice() {
		$choicesArr = Doctrine_Query::create()
		->select('o.id, o.name')
		->from('Group o')
		->fetchArray();

		$choices = array();
		foreach ($choicesArr as $value) {
			$choices[$value['id']] =  $value['name'];
		}

		return $choices;
	}

	function get_actions() {
		$html = '';
		$html .= '<a href="./'.$this->id.'/edit/"><img title="Düzenle" src="'.pjango_ini_get('ADMIN_MEDIA_URL').'/img/icons/small/addchange.png"/></a>&nbsp;';
		$html .= '<a href="./'.$this->id.'/delete/"><img title="Sil" src="'.pjango_ini_get('ADMIN_MEDIA_URL').'/img/icons/small/archive.png"/></a>';

		return $html;
	}
}