PhoneType:   
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        name: string(35)             


Phone:   
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        phone: string(35)       
                    
        phone_type_id: integer

    relations:
        PhoneType:
            foreignType: one           
                  

EmailType:   
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        name: string(35)             


Email:   
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        email: string(100)       
                    
        email_type_id: integer
 
    relations:
        EmailType:
            foreignType: one
            
AddressType:   
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true
            
        name: string(35)             


Address:   
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true

        name: string(100)               
        address: string(100)      
                    
        address_type_id: integer
 
    relations:
        AddressType:
            foreignType: one            

AddressMeta:  
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true 
        address_id: integer
        meta_key: string(255)
        meta_value: string               
    relations:
        Address:
            local: address_id
            foreign: id        
        
Contact:   
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true

        first_name: string(100)
        last_name: string(100) 
    relations:
        Phones:
            class: Phone
            local: contact_id
            foreign: phone_id
            refClass: ContactPhone
        Emails:
            class: Email
            local: contact_id
            foreign: email_id
            refClass: ContactEmail
        Addresses:
            class: Email
            local: contact_id
            foreign: address_id
            refClass: ContactAddress            


ContactMeta:  
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true 
        contact_id: integer
        meta_key: string(255)
        meta_value: string               
    relations:
        Contact:
            local: contact_id
            foreign: id      


ContactPhone:
    columns:
        contact_id:
            type: integer
            primary: true
        phone_id:
            type: integer
            primary: true
            
ContactEmail:
    columns:
        contact_id:
            type: integer
            primary: true
        email_id:
            type: integer
            primary: true            

ContactAddress:
    columns:
        contact_id:
            type: integer
            primary: true
        address_id:
            type: integer
            primary: true    


User:  
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true   
        username:  
            type: string(35)
            unique: true   
        displayname: string(35) 
        email:
            type: string(255)
            email: true    
        password: string(255)
        is_staff: boolean        
        is_active: boolean
        is_superuser: boolean
        last_login: timestamp
        date_joined: date
        
        contact_id: integer
                
    relations:
        Contact:
            local: contact_id
            foreign: id
                                    