Permission:
    tableName: auth_permission
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true   
        name:  string(50)
        codename:  string(100)        
        content_type_id: integer
                
    relations:
        ContentType:
            local: content_type_id
            foreign: id        
            
Group:
    tableName: auth_group            
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true   
        name:  string(100)
        site_id: integer
    relations:
        Site:
            local: site_id
            foreign: id         
        Permissions:
            foreignAlias: Groups
            class: Permission
            refClass: GroupPermission

GroupPermission:
    tableName: auth_group_permissions
    columns:
        group_id:
            type: integer
            primary: true
        permission_id:
            type: integer
            primary: true
    relations:
        Group:
            foreignAlias: GroupPermissions
        Permission:
            foreignAlias: PermissionGroups
            
User:  
    tableName: auth_user
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true   
        username:  
            type: string(35)
            unique: true   
        displayname: string(35) 
        email:
            type: string(255)
            email: true    
        password: string(255)
        is_staff: boolean        
        is_active: boolean
        is_superuser: boolean
        last_login: timestamp
        date_joined: date
        
        contact_id: integer
        site_id: integer
    relations:
        Site:
            local: site_id
            foreign: id        
        Groups:
            class: Group
            refClass: UserGroup
            foreignAlias: Users
        Permissions:
            class: Permission
            refClass: UserPermission
            foreignAlias: Users                  
        
                                
UserGroup:
    tableName: auth_user_groups
    columns:
        user_id:
            type: integer
            primary: true
        group_id:
            type: integer
            primary: true
    relations:
        User:
            foreignAlias: UserGroups
        Group:
            foreignAlias: GroupUsers           
                
UserPermission:
    tableName: auth_user_permissions
    columns:
        user_id:
            type: integer
            primary: true
        permission_id:
            type: integer
            primary: true
    relations:
        User:
            foreignAlias: UserPermissions
        Permission:
            foreignAlias: PermissionUsers                                          