<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Post extends BasePost
{
	const TYPE_POST = "post";
	const TYPE_PAGE = "page";
	
	const STATUS_DRAFT = 'draft';
	const STATUS_PUBLISHED = 'published';
	const STATUS_PRIVATE = 'private';
	const STATUS_ARCHIVE = 'archive';
	
	public static function getStatusChoices() {
		$choices = array(
		self::STATUS_DRAFT=>pjango_gettext("post.status.draft"),
		self::STATUS_PUBLISHED=>pjango_gettext("post.status.published"),
		self::STATUS_PRIVATE=>pjango_gettext("post.status.private"),
		self::STATUS_ARCHIVE=>pjango_gettext("post.status.archive"));
	
		return $choices;
	}	
	
	public function get_absolute_url() {
		$siteUrl = pjango_ini_get('SITE_URL');
		return sprintf('%s/%s/%s', $siteUrl, $this->post_type, $this->get_slug());
	}	
	
	function get_title() {
		return  $this->Translation[pjango_ini_get('LANGUAGE_CODE')]->title;		
	}
	
	function get_slug() {
		return  $this->Translation[pjango_ini_get('LANGUAGE_CODE')]->slug;
	}	
	
	function get_content() {
		return  $this->Translation[pjango_ini_get('LANGUAGE_CODE')]->content;		
	}	
	
	function get_excerpt() {
		return  $this->Translation[pjango_ini_get('LANGUAGE_CODE')]->excerpt;
	}	
	
	public function get_image() {
	
		$contentType = ContentType::get_for_model('Post');
		$metaData = PjangoMeta::getMeta($contentType->id, $this->id, 'images');
	
		if ($metaData) {
			$images = explode('|', $metaData->meta_value);
			return $images[0];
		}
	}	
	
	public function get_images() {
		$retval = array();
		
		$contentType = ContentType::get_for_model('Post');
		$metaData = PjangoMeta::getMeta($contentType->id, $this->id, 'images');
	
		if ($metaData && strlen($metaData->meta_value)>1) {
			$retval = explode('|', $metaData->meta_value);			
		}
		
		return $retval;
	}	
}