<?php

/**
 * PostCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    {P}jango
 * @subpackage ##SUBPACKAGE##
 * @author     Hasan Basri Ateş <hbasria@4net.com.tr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PostCategory extends BasePostCategory
{
	public static function findAllAsChoice($taxonomy = 'post') {
		$choices = array();
		$tree = false;
		$lng = pjango_ini_get('LANGUAGE_CODE');
		
		$treeObject = Doctrine::getTable('PostCategory')->getTree();
		$rootColumnName = $treeObject->getAttribute('rootColumnName');
		
		foreach ($treeObject->fetchRoots() as $root) {
			$options = array('root_id' => $root->$rootColumnName);
			
			
			if ($root->taxonomy == $taxonomy){
				$tree = $treeObject->fetchTree($options);
			}
		}
		
		if (!$tree) return $choices;
	
		foreach ($tree as $node) {
			$choices[$node['id']] =  str_repeat('--', $node['level']).$node->Translation[$lng]->name;
		}
			
		return $choices;
	}	
	
	function get_slug() {
		$lng = pjango_ini_get('LANGUAGE_CODE');
		return  $this->Translation[$lng]->slug;
	}	
	
	function get_name() {
		$lng = pjango_ini_get('LANGUAGE_CODE');
		return  $this->Translation[$lng]->name;
	}	
	
	function get_name_with_level() {
		$lng = pjango_ini_get('LANGUAGE_CODE');
		return  str_repeat('--', $this->level).$this->Translation[$lng]->name;
	}	

}