<?php

/**
 * Settings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    {P}jango
 * @subpackage ##SUBPACKAGE##
 * @author     Hasan Basri Ateş <hbasria@4net.com.tr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Settings extends BaseSettings
{
    public static function get_or_create($name, $category, $siteId = false){
    	if (!$siteId) $siteId = SITE_ID;

        $setting = Doctrine_Query::create()
            ->from('Settings s')
            ->where('s.site_id = ? AND s.name = ? AND s.category = ?', array($siteId, $name, $category))
            ->fetchOne();
        
        if(!$setting){
            $setting = new Settings();
            $setting->name = $name;
            $setting->category = $category;
            $setting->site_id = $siteId;
            $setting->save();
        }
        
        return $setting;
    }
    
    public static function saveFromArray($category, $data = array(), $siteId = false) {
        if (!$siteId) $siteId = SITE_ID;
        
        if (is_array($data)){   
            foreach ($data as $key => $value) {
                $setting = Settings::get_or_create($key, $category, $siteId);
                $setting->value = $value;
                $setting->site_id = $siteId;
                $setting->save();
            }
        }
    
    }    
}