<?php

/**
 * Site
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Site extends BaseSite
{
	const TYPE_INDIVIDUAL = 'individual'; //Corporate|Individual
	const TYPE_CORPORATE = 'corporate'; //Corporate|Individual
	
	
	public static function get_current() {
		return Doctrine_Query::create()
			->from('Site o')
			->where('o.id = ?', SITE_ID)
			->fetchOne();
	}
}