<?php

/**
 * ContentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContentType extends BaseContentType
{
	public static function findAllAsChoice() {
		$choicesArr = Doctrine_Query::create()
		    ->from('ContentType o')
		    ->fetchArray();
		    
		$choices = array('-' => '----------');
		foreach ($choicesArr as $value) {
			$choices[$value['id']] =  $value['app_label'].'.'.$value['model'];
		}
		
		return $choices;
	}
		
	public static function get_for_model($model, $app_label=false, $name=false) {
		
		$q = Doctrine_Query::create()
	            ->from('ContentType o')          
	            ->where('o.model = ?', array($model));
		
		if ($app_label){
			$q->addWhere('o.app_label = ?', array($app_label));
		}
		
		$contentType = $q->fetchOne();

		if(!$contentType){
			$contentType = new ContentType();
			$contentType->app_label = $app_label;
			$contentType->model = $model;
			$contentType->name = $app_label.' '.$model;
			$contentType->save();
		}	            
	            
		return $contentType;		
	}
	
	public static function get_for_id($id) {
		
		$ct = Doctrine_Query::create()
	            ->from('ContentType o')          
	            ->where('o.id = ?',$id)
	            ->fetchOne(); 
	    return $ct;		
	}	
	
	public function get_object_for_this_type($id) {
		if(strlen($this->model)>0){
			$obj = Doctrine_Query::create()
				->from($this->model.' o')
				->where('o.id = ?',$id)
				->fetchOne();		
			if ($obj) return $obj;
		}

		return false;		
	}
}