<?php

/**
 * PhoneType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PhoneType extends BasePhoneType
{
	const TYPE_MOBILE 	= 1; 
	const TYPE_WORK		= 2; 
	const TYPE_HOME 	= 3; 
	const TYPE_MAIN	 	= 4; 
	const TYPE_WORKFAX	= 5;
	const TYPE_HOMEFAX 	= 6;
	
	public static function findAllAsChoice() {
		$choicesArr = Doctrine_Query::create()
			->select('o.id, o.name')
		    ->from('PhoneType o')
		    ->fetchArray();
		    
		$choices = array();
		foreach ($choicesArr as $value) {
			$choices[$value['id']] =  $value['name'];
		}
		
		return $choices;
	}	

}