<?php

/**
 * PjangoMeta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    {P}jango
 * @subpackage ##SUBPACKAGE##
 * @author     Hasan Basri Ateş <hbasria@4net.com.tr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PjangoMeta extends BasePjangoMeta
{
	public static function getMeta($contentTypeId, $objectId, $metaKey = false) {
	    $isteId = pjango_ini_get('SITE_ID');
		$q = Doctrine_Query::create()
			->from('PjangoMeta pm')
			->addWhere('pm.site_id = ? AND pm.content_type_id = ? AND pm.object_id = ?', array($isteId, $contentTypeId, $objectId));
		
		if ($metaKey){
			$q = $q->addWhere('pm.meta_key = ?', $metaKey)
			->fetchOne();
		}else{
			$q = $q->execute();
		}
				
		return $q;
	}
	
	public static function setMeta($contentTypeId, $objectId, $metaKeys = false, $metaValues = false) {
	    $isteId = pjango_ini_get('SITE_ID');
		
// 		metaları bul
		if (!is_array($metaKeys)){
			$metaKeys = array();
			// 		meta_
			foreach ($metaValues as $key => $value) {
				if(substr($key, 0, 5) == 'meta_'){
					$metaKeys[] = $key;
				}
			}
		}		
		
		if (is_array($metaKeys) && is_array($metaValues)){
					
			foreach ($metaKeys as $key) {
				if (!isset($metaValues[$key])) continue;
					
				$meta = PjangoMeta::getMeta($contentTypeId, $objectId, $key);					
				if (!$meta) $meta = new PjangoMeta();
					
				$meta->content_type_id = $contentTypeId;
				$meta->site_id = $isteId;
				$meta->object_id = $objectId;
				$meta->meta_key = $key;
				
				if(is_array($metaValues[$key])){
				    $meta->meta_value = serialize($metaValues[$key]);
				}else {
				$meta->meta_value = $metaValues[$key];
				}				
				
				$meta->save();
			}
		}
		
	}

}