<?php

/**
 * PjangoMeta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    {P}jango
 * @subpackage ##SUBPACKAGE##
 * @author     Hasan Basri Ateş <hbasria@4net.com.tr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PjangoMeta extends BasePjangoMeta
{
	public static function getMeta($contentTypeId, $objectId, $metaKey = false) {
		$q = Doctrine_Query::create()
			->from('PjangoMeta pm')
			->addWhere('pm.content_type_id = ? AND pm.object_id = ?', array($contentTypeId, $objectId));
		
		if ($metaKey){
			$q = $q->addWhere('pm.meta_key = ?', $metaKey)
			->fetchOne();
		}else{
			$q = $q->execute();
		}
				
		return $q;
	}
	
	public static function setMeta($contentTypeId, $objectId, $metaKeys = false, $metaValues = false) {
		
		if (is_array($metaKeys) && is_array($metaValues)){
					
			foreach ($metaKeys as $key) {
				if (!isset($metaValues[$key])) continue;
					
				$meta = PjangoMeta::getMeta($contentTypeId, $objectId, $key);					
				if (!$meta) $meta = new PjangoMeta();
					
				$meta->content_type_id = $contentTypeId;
				$meta->object_id = $objectId;
				$meta->meta_key = $key;
				$meta->meta_value = $metaValues[$key];
				$meta->save();
			}
		}
		
	}

}