<?php

/**
 * PjangoList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PjangoList extends BasePjangoList
{
	public static function findAllAsChoice($rootId = 1) {
		$choices = array('root'=>'Root');
		$tree = false;
		$lng = pjango_ini_get('LANGUAGE_CODE');
	
		$treeObject = Doctrine::getTable('PjangoList')->getTree();
		$rootColumnName = $treeObject->getAttribute('rootColumnName');
	
		foreach ($treeObject->fetchRoots() as $root) {
			$options = array('root_id' => $root->$rootColumnName);
	
	
			if ($root->root_id == $rootId){
				$tree = $treeObject->fetchTree($options);
			}
		}
	
		if (!$tree) return $choices;
	
		foreach ($tree as $node) {
			$choices[$node['id']] =  str_repeat('--', $node['level']).$node->Translation[$lng]->name;
		}
			
		return $choices;
	}
	

}