<?php

/**
 * PjangoToken
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    {P}jango
 * @subpackage ##SUBPACKAGE##
 * @author     Hasan Basri Ateş <hbasria@4net.com.tr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PjangoToken extends BasePjangoToken
{
	const STATUS_NEW = 'new';
	const STATUS_USED = 'used';
	const STATUS_APPROVED = 'approved';
	
	
	public static function make_token($contentType, $objectId) {
		
		$ctype = ContentType::get_for_model($contentType);
		
		$_instance = new self();
		$_instance->token = md5(uniqid(rand(), true));
		$_instance->status = self::STATUS_NEW;
		$_instance->expires =date('Y-m-d', time()+(7 * 24 * 60 * 60));
		$_instance->object_id = $objectId;
		$_instance->ContentType = $ctype;
		$_instance->save();
		
		return $_instance;
		
	}
	
	public static function check_token($tokenStr) {
		$token = Doctrine_Query::create()
			->from('PjangoToken t')
            ->where('t.token = ? AND t.status = ?', array($tokenStr, PjangoToken::STATUS_NEW))
            ->fetchOne();
            
        if ($token) return $token;
        else return false;
		
	}

}