<?php

/**
 * PostCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    {P}jango
 * @subpackage ##SUBPACKAGE##
 * @author     Hasan Basri Ateş <hbasria@4net.com.tr>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PostCategory extends BasePostCategory
{
	public static function get_or_create_main_category($taxonomy = 'Post') {
		$category = Doctrine_Query::create()
			->from('PostCategory o')
			->where('o.site_id = ? AND o.taxonomy = ? AND o.level = 0', array(SITE_ID, $taxonomy))
			->fetchOne();

		if (!$category){
			$category = new PostCategory();
			$category->Translation['en']->name = $taxonomy.' Main Category';
			$category->Translation['en']->slug = ucfirst($taxonomy).'-main-category';
			
			$lng = pjango_ini_get('LANGUAGE_CODE');
			if($lng != 'en'){
				$category->Translation[$lng]->name = $taxonomy.' '.__('Main Category');
				$category->Translation[$lng]->slug = ucfirst($taxonomy).'-'.__('main-category');				
			}

			$category->site_id = SITE_ID;
			$category->taxonomy = $taxonomy;
			$category->save();
			$treeObject = Doctrine_Core::getTable('PostCategory')->getTree();
			$treeObject->createRoot($category);			
		}
		
		return $category;
	}
	
	public static function findAllAsChoice($taxonomy = 'Post') {
		$choices = array();
		
		$categories = Doctrine_Query::create()
    		->from('PostCategory o')
    		->leftJoin('o.Translation t')
    		->where('o.site_id = ? AND o.taxonomy = ?',array(SITE_ID, $taxonomy))
		    ->orderBy('o.lft')
		    ->execute();
		
		foreach ($categories as $categoryItem) {
			$choices[$categoryItem->id] =  str_repeat('--', $categoryItem->level).$categoryItem->get_name();
		}
			
		return $choices;
	}	
	
	public static function findBySlug($slug, $taxonomy) {	
	    $p = Doctrine_Query::create()
    	    ->from('PostCategory o')
    	    ->leftJoin('o.Translation t')
    	    ->where('o.site_id = ? AND o.taxonomy = ? AND t.slug = ?',array(SITE_ID, $taxonomy, $slug))
    	    ->fetchOne();
	
	    if($p){	
	        return Doctrine_Query::create()
    	        ->from('PostCategory o')
    	        ->leftJoin('o.Translation t')
    	        ->where('o.id = ? ',array($p->id))
    	        ->fetchOne();
	    }else {
	        return false;
	    }
	}	
	
	function get_slug() {
		return translation($this->Translation, 'slug');
	}	
	
	function get_name() {
		return translation($this->Translation, 'name');			
	}	
	
	function get_name_with_level() {
		return  str_repeat('--', $this->level).$this->get_name();
	}	

}