Comment:  
    columns:
        id:
            type: integer
            primary: true  
            notnull: true
            autoincrement: true                  
        comment: string
        submit_date: timestamp
        ip_address: string(100)
        is_public: boolean
        
        user_id: integer
        content_type_id: integer
        object_pk: integer
        
    relations:
        User:
            local: user_id
            foreign: id          
        ContentType:
            local: content_type_id
            foreign: id                                    